Add node and yarn to dev dependencies
edgedb/edgedb pull request #3725
Opened 2022-04-05 21:35 UTC by fmoor

2022-04-05 21:35 UTC, elprans approved these changes

2022-04-05 21:36 UTC, msullivan approved these changes

2022-04-05 21:43 UTC, colinhacks requested changes

2022-04-05 21:43 UTC, colinhacks commented on docs/reference/dev.rst
> +* nodejs;
Let's specify Node.js 14+ and Yarn v1

2022-04-07 23:14 UTC, msullivan approved these changes

2022-04-07 23:14 UTC, merged