Clarify link property usage.
edgedb/edgedb pull request #4623
Opened 2022-11-03 10:21 UTC by vpetrovykh

Update the docs with the clarification that link properties should be used with many-to-many relationships.

Fixes #4614

2022-11-03 23:21 UTC, msullivan approved these changes

2022-11-07 22:39 UTC, raddevon requested changes
Noticed one typo. Looks great otherwise. Wonderful explanation!

2022-11-07 22:39 UTC, raddevon commented on docs/datamodel/links.rst
> +described by the link and the *target obejct*. Thus it makes sense to separate
Typo: `obejct` -> `object`

2022-11-07 23:15 UTC, raddevon approved these changes

2022-11-18 15:11 UTC, raddevon approved these changes

2022-12-01 17:16 UTC, i0bs approved these changes

2022-12-07 18:02 UTC, merged