Expand contributing documentation
edgedb/edgedb pull request #5100
Opened 2023-02-27 12:31 UTC by raddevon

2023-02-27 18:26 UTC, 1st1 commented on docs/guides/contributing/code.rst
> +    help guide you to the finish line.
This sounds a tad harsh to me. How about:

```suggestion
    Code-changing pull requests without adding new tests might take
    longer time to be reviewed and merged.
```

2023-02-28 12:46 UTC, raddevon commented
Forgot to tag you for a review on this, @jaclarke. If you have a chance, see if you notice any glaring omissions or inaccuracies.

2023-03-10 19:35 UTC, vpetrovykh requested changes
Aside from a couple of typos LGTM.

2023-03-10 19:35 UTC, vpetrovykh commented on docs/guides/contributing/documentation.rst
> +Use the ``versionchanged`` directive to mark content related to a change in to
```suggestion
Use the ``versionchanged`` directive to mark content related to a change in
```

2023-03-10 19:35 UTC, vpetrovykh commented on docs/guides/contributing/index.rst
> +documentation .
```suggestion
documentation.
```

2023-03-13 10:16 UTC, vpetrovykh approved these changes

2023-03-13 12:21 UTC, jaclarke commented on docs/guides/contributing/documentation.rst
> +    will need to interrupt and restart the development server.
This behaviour is a bug. `yarn dev` should watch for docs changes and re-build automatically without needing to restart (with the small caveat that we can't communicate this update to nextjs hot reload, so you do have to manually refresh the page in the browser).

2023-03-13 14:50 UTC, merged