Add a special param token for normalization
edgedb/edgedb pull request #6330
Opened 2023-10-20 18:53 UTC by aljazerzen

2023-10-20 20:18 UTC, msullivan approved these changes

2023-10-20 20:19 UTC, elprans requested changes
This file is generated, you want to fix the template and run `make` in `.github`.

2023-10-23 13:41 UTC, aljazerzen commented
I've refactored whitespace in the generated yaml, see separate commits.

2023-10-24 04:42 UTC, elprans approved these changes

2023-10-24 07:18 UTC, merged